version: "1.0"
project:
  name: pycaret-diamond-prices
  docker_image: bodyworkml/bodywork-core:2.1.7
  DAG: serve-predictions
stages:
  serve-predictions:
    executable_module_path: serve_predictions.py
    requirements:
      - fastapi==0.68.1
      - pycaret[full]==2.3.3
      - uvicorn==0.15.0
    cpu_request: 0.5
    memory_request_mb: 150
    service:
      max_startup_time_seconds: 30
      replicas: 2
      port: 8000
      ingress: true
logging:
  log_level: INFO
